---
dataset_dir: inputs/dataset  # This is a comment
label_from: directory
data_preparation: custom
data_set_cache: memory
output_dir: outputs
log_dir: logs
checkpoint_dir: checkpoint
log_level: info
log_to: console
validation_rate: .3
input_shape: [64, 64, 3]
num_output_class: 6
callbacks:
- tensorboard
- checkpoint
hparam_tuning:
  learning_rate:
  - .1
  - .01
  - .001
  dropout:
  - .1
  - .2
  - .3
  optimizer:
  - adam
  - sgd
  epochs:
  - 2
  activation:
  - relu
  loss:
  - sparse_categorical_crossentropy
  batch_size:
  - 16
  - 32
hparam:
  activation: relu
  learning_rate: .001
  dropout: .3
  optimizer: adam
  epochs: 2
  loss: sparse_categorical_crossentropy
  batch_size: 32